version: "2"
run:
  go: "1.24"
  build-tags:
    - integration
    - unit
    - component
    - manual
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gelatoddd
    - gochecknoinits
    - goconst
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - paralleltest
    - predeclared
    - promlinter
    - recvcheck
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - testpackage
    - testsbuildtags
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^t\.Error\(
        - pattern: ^t\.Errorf\(
        - pattern: ^t\.Fatal\(
        - pattern: ^t\.Fatalf\(
        - pattern: ^t\.Fail\(
        - pattern: ^t\.FailNow\(
        - pattern: ^t\.Skip\(
        - pattern: ^t\.Skipf\(
        - pattern: ^t\.SkipNow\(
        - pattern: ^t\.Log\(
        - pattern: ^t\.Logf\(
      analyze-types: true
    testifylint:
      enable-all: true
      disable:
        - bool-compare
    custom:
      gelatoddd:
        type: module
      testsbuildtags:
        type: module
        settings:
          expected-tags:
            - unit
            - integration
            - component
            - manual
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - contrib
      - onetime
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/noodlensk/swedish-news)
  exclusions:
    generated: lax
    paths:
      - contrib
      - onetime
      - third_party$
      - builtin$
      - examples$
