version: '2.4'

services:
  grocery:
    build: ./
    command:
      - /app
      - -config
      - /etc/grocery/config/config.yaml
    restart: on-failure
    volumes:
      - ./grocery.db:/etc/grocery/storage/grocery.db
      - ./config.docker.yaml:/etc/grocery/config/config.yaml